### ISSUE TITLE
Implement Note

### ISSUE THREAD

**Issue by yitsushi** [yitsushi/go-misskey#6]
- [ ] notes/conversation
 - [x] notes/children #53 
 - [x] notes/create #51 
 - [x] notes/delete #51 
 - [x] notes/mentions #52 
 - [x] notes/unrenote #52 
 - [x] notes/featured #45 
 - [x] notes/renotes #45 
 - [x] notes/replies #45 
 - [x] notes/show #45 
 - [x] notes/state #45 

Search:
 - [x] notes/search-by-tag #53 
 - [x] notes/search #45 

Timeline:
 - [x] notes/global-timeline #50
 - [x] notes/hybrid-timeline #50
 - [x] notes/local-timeline #50
 - [x] notes/user-list-timeline #50
 - [x] notes/timeline #50 

Polls:
 - [ ] notes/polls/recommendation
 - [ ] notes/polls/vote

Favorites:
 - [ ] notes/favorites/create
 - [ ] notes/favorites/delete

Watching:
 - [ ] notes/watching/create
 - [ ] notes/watching/delete

Reactions: (related: #14)
 - [x] notes/reactions #45 
 - [x] notes/reactions/create #49 
 - [x] notes/reactions/delete #49 

Extra:
 - [x] promo/read #49 

Documentation: https://misskey.io/api-doc#tag/notes

It will be more than one PR, most likely. This section has a ton of endpoints.
